{% set name = "snscrape" %}
{% set version = "0.4.3.20220106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snscrape-{{ version }}.tar.gz
  sha256: fd176765196ca17979be7f54e041f430e4cb23a5e651fa29cf3dc382258019f2

build:
  skip: true  # [py<38]
  entry_points:
    - snscrape = snscrape._cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools-scm
  run:
    - beautifulsoup4
    - filelock
    - lxml
    - python
    - pytz  # [py<39]
    - requests

test:
  imports:
    - snscrape
  commands:
    - pip check
    - snscrape --help
  requires:
    - pip

about:
  home: https://github.com/JustAnotherArchivist/snscrape
  summary: A social networking service scraper
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - angelinux
